# DLMS configuration

[DLMS]
scaler_prefix = [
    {name = "k", value = 3}
]
Enumerated_values_for_physical_units = [
    {unit=1, Unit="год"},
    {unit=2, Unit="мес"},
    {unit=3, Unit="нед"},
    {unit=4, Unit="дн"},
    {unit=5, Unit="ч"},
    {unit=6, Unit="мин"},
    {unit=7, Unit="с"},
    {unit=8, Unit="°"},
    {unit=9, Unit="°c"},
    {unit=10, Unit="валюта"},
    {unit=11, Unit="м"},
    {unit=12, Unit="м/с"},
    {unit=13, Unit="м³"},
    {unit=14, Unit="м³*"},
    {unit=15, Unit="м³/ч"},
    {unit=16, Unit="м³/ч*"},
    {unit=17, Unit="м³/дн"},
    {unit=18, Unit="м³/дн*"},
    {unit=19, Unit="л"},
    {unit=20, Unit="кг"},
    {unit=21, Unit="Н"},
    {unit=22, Unit="Нм"},
    {unit=23, Unit="Па"},
    {unit=24, Unit="100000 Н/м²"},
    {unit=25, Unit="Дж"},
    {unit=26, Unit="Дж/ч"},
    {unit=27, Unit="Вт", scaler=3},
    {unit=28, Unit="В*А", scaler=3},
    {unit=29, Unit="ВАР", scaler=3},
    {unit=30, Unit="Вт*ч", scaler=3},
    {unit=31, Unit="В*А*ч", scaler=3},
    {unit=32, Unit="ВАР*ч", scaler=3},
    {unit=33, Unit="А"},
    {unit=34, Unit="к"},
    {unit=35, Unit="В"},
    {unit=36, Unit="В/м"},
    {unit=37, Unit="ф"},
    {unit=38, Unit="Ом"},
    {unit=39, Unit="Ом*м"},
    {unit=40, Unit="Вб"},
    {unit=41, Unit="Тл"},
    {unit=42, Unit="А/м"},
    {unit=43, Unit="Гн"},
    {unit=44, Unit="Гц"},
    {unit=45, Unit="1/(Вт*ч)"},
    {unit=46, Unit="1/(ВАР*ч)"},
    {unit=47, Unit="1/(В*А*ч)"},
    {unit=48, Unit="В²*ч"},
    {unit=49, Unit="А²*ч"},
    {unit=50, Unit="кг/с"},
    {unit=51, Unit="см"},
    {unit=52, Unit="К"},
    {unit=53, Unit="1/(В²*ч)"},
    {unit=54, Unit="1/(А²*ч)"},
    {unit=55, Unit="1/м³"},
    {unit=56, Unit="%"},
    {unit=57, Unit="А*ч"},
    {unit=58, Unit="зарезервировано"},
    {unit=59, Unit="зарезервировано"},
    {unit=60, Unit="3600 Дж/м³"},
    {unit=61, Unit="Дж/м³"},
    {unit=62, Unit="моль %"},
    {unit=63, Unit="г/м³"},
    {unit=64, Unit="Па*с"},
    {unit=65, Unit="Дж/кг"},
    {unit=66, Unit="г/см²"},
    {unit=67, Unit="атм"},
    {unit=68, Unit="зарезервировано"},
    {unit=69, Unit="зарезервировано"},
    {unit=70, Unit="дБм"},
    {unit=71, Unit="дБмкВ"},
    {unit=72, Unit="дБ"},
    {unit=73, Unit="зарезервировано"},
    {unit=74, Unit="зарезервировано"},
    {unit=75, Unit="зарезервировано"},
    {unit=76, Unit="зарезервировано"},
    {unit=77, Unit="зарезервировано"},
    {unit=78, Unit="зарезервировано"},
    {unit=79, Unit="зарезервировано"},
    {unit=80, Unit="зарезервировано"},
    {unit=81, Unit="зарезервировано"},
    {unit=82, Unit="зарезервировано"},
    {unit=83, Unit="зарезервировано"},
    {unit=84, Unit="зарезервировано"},
    {unit=85, Unit="зарезервировано"},
    {unit=86, Unit="зарезервировано"},
    {unit=87, Unit="зарезервировано"},
    {unit=88, Unit="зарезервировано"},
    {unit=89, Unit="зарезервировано"},
    {unit=90, Unit="зарезервировано"},
    {unit=91, Unit="зарезервировано"},
    {unit=92, Unit="зарезервировано"},
    {unit=93, Unit="зарезервировано"},
    {unit=94, Unit="зарезервировано"},
    {unit=95, Unit="зарезервировано"},
    {unit=96, Unit="зарезервировано"},
    {unit=97, Unit="зарезервировано"},
    {unit=98, Unit="зарезервировано"},
    {unit=99, Unit="зарезервировано"},
    {unit=100, Unit="зарезервировано"},
    {unit=101, Unit="зарезервировано"},
    {unit=102, Unit="зарезервировано"},
    {unit=103, Unit="зарезервировано"},
    {unit=104, Unit="зарезервировано"},
    {unit=105, Unit="зарезервировано"},
    {unit=106, Unit="зарезервировано"},
    {unit=107, Unit="зарезервировано"},
    {unit=108, Unit="зарезервировано"},
    {unit=109, Unit="зарезервировано"},
    {unit=110, Unit="зарезервировано"},
    {unit=111, Unit="зарезервировано"},
    {unit=112, Unit="зарезервировано"},
    {unit=113, Unit="зарезервировано"},
    {unit=114, Unit="зарезервировано"},
    {unit=115, Unit="зарезервировано"},
    {unit=116, Unit="зарезервировано"},
    {unit=117, Unit="зарезервировано"},
    {unit=118, Unit="зарезервировано"},
    {unit=119, Unit="зарезервировано"},
    {unit=120, Unit="зарезервировано"},
    {unit=121, Unit="зарезервировано"},
    {unit=122, Unit="зарезервировано"},
    {unit=123, Unit="зарезервировано"},
    {unit=124, Unit="зарезервировано"},
    {unit=125, Unit="зарезервировано"},
    {unit=126, Unit="зарезервировано"},
    {unit=127, Unit="зарезервировано"},
    {unit=128, Unit="in"},
    {unit=129, Unit="ft"},
    {unit=130, Unit="lb"},
    {unit=131, Unit="°f"},
    {unit=132, Unit="°r"},
    {unit=133, Unit="sq. in"},
    {unit=134, Unit="sq ft"},
    {unit=135, Unit="ac"},
    {unit=136, Unit="cu in"},
    {unit=137, Unit="cu ft"},
    {unit=138, Unit="ac ft"},
    {unit=139, Unit="gal(imp)"},
    {unit=140, Unit="gal(us)"},
    {unit=141, Unit="lbf"},
    {unit=142, Unit="psi"},
    {unit=143, Unit="lb/cu ft"},
    {unit=144, Unit="lb/(ft .s)"},
    {unit=145, Unit="sq ft/s"},
    {unit=146, Unit="btu"},
    {unit=147, Unit="thm(ec)"},
    {unit=148, Unit="thm(us)"},
    {unit=149, Unit="btu/lb"},
    {unit=150, Unit="btu/cu ft"},
    {unit=151, Unit="cu ft rv"},
    {unit=152, Unit="ft/s"},
    {unit=153, Unit="cu ft/s"},
    {unit=154, Unit="cu ft/min"},
    {unit=155, Unit="cu ft/h"},
    {unit=156, Unit="cu ft/d"},
    {unit=157, Unit="ac ft/s"},
    {unit=158, Unit="ac ft/min"},
    {unit=159, Unit="ac ft/h"},
    {unit=160, Unit="ac ft/d"},
    {unit=161, Unit="gal(imp) rv"},
    {unit=162, Unit="gal(imp)/s"},
    {unit=163, Unit="gal(imp)/min"},
    {unit=164, Unit="gal(imp)/h"},
    {unit=165, Unit="gal(imp)/d"},
    {unit=166, Unit="gal(us) rv"},
    {unit=167, Unit="gal(us)/s"},
    {unit=168, Unit="gal(us)/min"},
    {unit=169, Unit="gal(us)/h"},
    {unit=170, Unit="gal(us)/d"},
    {unit=171, Unit="btu/s"},
    {unit=172, Unit="btu/min"},
    {unit=173, Unit="btu/h"},
    {unit=174, Unit="btu/d"},
    {unit=175, Unit="зарезервировано"},
    {unit=176, Unit="зарезервировано"},
    {unit=177, Unit="зарезервировано"},
    {unit=178, Unit="зарезервировано"},
    {unit=179, Unit="зарезервировано"},
    {unit=180, Unit="зарезервировано"},
    {unit=181, Unit="зарезервировано"},
    {unit=182, Unit="зарезервировано"},
    {unit=183, Unit="зарезервировано"},
    {unit=184, Unit="зарезервировано"},
    {unit=185, Unit="зарезервировано"},
    {unit=186, Unit="зарезервировано"},
    {unit=187, Unit="зарезервировано"},
    {unit=188, Unit="зарезервировано"},
    {unit=189, Unit="зарезервировано"},
    {unit=190, Unit="зарезервировано"},
    {unit=191, Unit="зарезервировано"},
    {unit=192, Unit="зарезервировано"},
    {unit=193, Unit="зарезервировано"},
    {unit=194, Unit="зарезервировано"},
    {unit=195, Unit="зарезервировано"},
    {unit=196, Unit="зарезервировано"},
    {unit=197, Unit="зарезервировано"},
    {unit=198, Unit="зарезервировано"},
    {unit=199, Unit="зарезервировано"},
    {unit=200, Unit="зарезервировано"},
    {unit=201, Unit="зарезервировано"},
    {unit=202, Unit="зарезервировано"},
    {unit=203, Unit="зарезервировано"},
    {unit=204, Unit="зарезервировано"},
    {unit=205, Unit="зарезервировано"},
    {unit=206, Unit="зарезервировано"},
    {unit=207, Unit="зарезервировано"},
    {unit=208, Unit="зарезервировано"},
    {unit=209, Unit="зарезервировано"},
    {unit=210, Unit="зарезервировано"},
    {unit=211, Unit="зарезервировано"},
    {unit=212, Unit="зарезервировано"},
    {unit=213, Unit="зарезервировано"},
    {unit=214, Unit="зарезервировано"},
    {unit=215, Unit="зарезервировано"},
    {unit=216, Unit="зарезервировано"},
    {unit=217, Unit="зарезервировано"},
    {unit=218, Unit="зарезервировано"},
    {unit=219, Unit="зарезервировано"},
    {unit=220, Unit="зарезервировано"},
    {unit=221, Unit="зарезервировано"},
    {unit=222, Unit="зарезервировано"},
    {unit=223, Unit="зарезервировано"},
    {unit=224, Unit="зарезервировано"},
    {unit=225, Unit="зарезервировано"},
    {unit=226, Unit="зарезервировано"},
    {unit=227, Unit="зарезервировано"},
    {unit=228, Unit="зарезервировано"},
    {unit=229, Unit="зарезервировано"},
    {unit=230, Unit="зарезервировано"},
    {unit=231, Unit="зарезервировано"},
    {unit=232, Unit="зарезервировано"},
    {unit=233, Unit="зарезервировано"},
    {unit=234, Unit="зарезервировано"},
    {unit=235, Unit="зарезервировано"},
    {unit=236, Unit="зарезервировано"},
    {unit=237, Unit="зарезервировано"},
    {unit=238, Unit="зарезервировано"},
    {unit=239, Unit="зарезервировано"},
    {unit=240, Unit="зарезервировано"},
    {unit=241, Unit="зарезервировано"},
    {unit=242, Unit="зарезервировано"},
    {unit=243, Unit="зарезервировано"},
    {unit=244, Unit="зарезервировано"},
    {unit=245, Unit="зарезервировано"},
    {unit=246, Unit="зарезервировано"},
    {unit=247, Unit="зарезервировано"},
    {unit=248, Unit="зарезервировано"},
    {unit=249, Unit="зарезервировано"},
    {unit=250, Unit="зарезервировано"},
    {unit=251, Unit="зарезервировано"},
    {unit=252, Unit="зарезервировано"},
    {unit=253, Unit="расширенная"},
    {unit=254, Unit="другое"},
    {unit=255, Unit="ед"}]
