[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backed = "setuptools.build_meta"

[project]
name = "DLMS_SPODES"
version = "0.23.3"
authors = [
    {name="Serj Kotilevski", email="youserj@outlook.com"}
]
description="dlms-spodes"
readme = "README.md"
requires-python = ">=3.11"
keywords=['dlms', 'string', 'constant', 'values']
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]